version: 2

sources:

  - name: csv
    database: puffy
    schema: raw
    tables:
      - name: events
        description: raw events from ecomm website
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}